### ISSUE TITLE
Crash during the first part of episode 1

### ISSUE THREAD

**Issue by ramp444** [ScarletStudy/DGS1-Android-Release#10]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Samsung Galaxy S7

**Android Version?**
8.0.0

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No

**Is your device rooted?** (If you don't know what this means, then most likely no)
No

### Your issue

**Please describe the issue you are experiencing:**

First off thanks for your effort!!! game looks amazing but I can't get past the first part of the game.
Game is always crashing after this point

> (That's right... That was when the incident
occurred.)

Screen fade but then it send me back to save screen :(
I uninstalled and reinstalled the game and Iris patcher alot but the crash didn't go.

Thank you in advance!

**Comment by an-error42** [comment]
Hello, this seems to be the same problem that has been reported before.

We've already implemented a fix and we're in the process of testing it, it'll be ready in 2.3.1 update which will be out soon.

Meanwhile, can you confirm the following please:

* Does DGS crash with "App stopped working" message or it just restarts?
* Restore the game from IrisMobile (via "Restore Original Game"), and play Episode 1 again, does the crash occur in the original DGS as well?

**Comment by ramp444** [comment]
Wow fast! it's as you what said the game restart without warning.
I'll use restore original game and keep you updated. Thank you!

**Comment by ramp444** [comment]
After using restore original game and playing episode 1 again game is also crashing after this point.

**Comment by an-error42** [comment]
From Episode 1, select "Recess" chapter and play a few moments till you're here as shown in the screenshot below, does DGS crash *after* this point?

![bluestacks_2018-10-05_15-07-02](https://user-images.githubusercontent.com/35239724/46537212-0563e700-c8b1-11e8-9586-4b65df8d7377.png)

Here's the relevant backlog:

![bluestacks_2018-10-05_15-07-23](https://user-images.githubusercontent.com/35239724/46537252-16145d00-c8b1-11e8-8d79-f16621b692d2.png)

It doesn't matter if you're playing with the patched or the original DGS, but do note that this will involve spoilers for Episode 1 obviously.

**Comment by ramp444** [comment]
Correct, it stopped here after fade
![](https://user-images.githubusercontent.com/43874557/46542138-5df1af00-c8c6-11e8-8fda-688710480a08.jpg)

**Comment by an-error42** [comment]
It's pretty much confirmed at this point. Please wait for the 2.3.1 update which will come out soon, a fix has been implemented there.

**Comment by an-error42** [comment]
An update has been published that includes a fix for this very issue.
Please update the patched DGS1 from IrisMobile via the "Apply Patch" button, and test those two scenes again.

Additionally, someone with the same problem has reported that DGS1 crashes on yet another two scenes (Spoilers for Episode 2, won't embed them):

[Screenshot_20181008-100345_The_Great_Ace_Attorney.jpg](https://cdn.discordapp.com/attachments/459464907969265673/498767728153198592/Screenshot_20181008-100345_The_Great_Ace_Attorney.jpg)
[Screenshot_20181008-092115_The_Great_Ace_Attorney.jpg](https://cdn.discordapp.com/attachments/459464907969265673/498767728589668362/Screenshot_20181008-092115_The_Great_Ace_Attorney.jpg)

Let us know if the update has fixed the crash in all of those 4 scenes so far (or the first two if you haven't played Episode 2 yet).

**Comment by an-error42** [comment]
While as of 2.3.1.1 some of those crashes have been fixed, not all of the crashes have been fixed yet on the affected devices.

However, someone who does have an affected device has made the following breakthrough:

> Here's a funny story: you know those flashback crashes I had? Well, it turns out I didn't have any by activating "Full Screen mode" on Game Tools (a standard Samsung tool, I think). I'll test on the japanese version

And indeed, the crashes are no longer in the Japanese version of the game as well.

Please give Game Tools a try and let us know about the results.

**Comment by Myebix** [comment]
What do I do if I'm not using a Samsung, meaning that I don't have the option to do that? I tried an app that's supposed to do the same thing, but it didn't work, the crashes still happened. I am also fully updated.

**Comment by wabberz** [comment]
Is your phone rooted?

**Comment by Myebix** [comment]
Nope.

**Comment by wabberz** [comment]
Which maker / model is your phone?
Android version?
Custom ROM?
Please describe when the crashes happen and if you can reproduce them.

**Comment by Myebix** [comment]
I have a Moto x4 
Android 8.0
No custom ROM
My crashes are happening the exact same as OP. Every time I try to play through, it crashes in the exact same spot. I've also tried all the suggested things in this thread.

**Comment by wabberz** [comment]
@Myebix were you able to solve this issue?

**Comment by DanielAyo** [comment]
Hi, I'm having the same issues described by the OP in the following comment

https://github.com/ScarletStudy/DGS1-Android-Release/issues/10#issuecomment-427390990

From Episode 1, select "Recess" chapter and play until you're here as shown below:

![Screenshot_20190414-172554](https://user-images.githubusercontent.com/18689653/56096309-6f072280-5ede-11e9-9e52-5526b7969369.png)

TGAA immediately restarts after this point consistently. 

The same result also occurs when loading from a previous save point.

About your device
Device Manufacturer / Model or Emulator / Version??
Nokia 6.1

Android Version?
9

Are you using a Custom ROM? (If you don't know what this means, then most likely no)
No

Is your device rooted? (If you don't know what this means, then most likely no)
No

Furthermore, I have the 2.4.0 patch applied to TGAA.

**Comment by wabberz** [comment]
Can you make the game crash in this way and then dump your tombstones so we can take a look?
Settings > System > About phone > Tap "Build number" until development settings are unlocked
then Settings > System > Developer options > Take bug report > Interactive
This should give you an archive with the tombstones.

**Comment by DanielAyo** [comment]
> 
> 
> Can you make the game crash in this way and then dump your tombstones so we can take a look?
> Settings > System > About phone > Tap "Build number" until development settings are unlocked
> then Settings > System > Developer options > Take bug report > Interactive
> This should give you an archive with the tombstones.

I've taken a bug report, I assume you're referring to following location within the archive zip file.

bugreport-example\FS\data\tombstones

There are 9 tombstone files within the folder, how should I send them?

Regards,

**Comment by Schness7** [comment]
Bumping this thread because this is the exact problem I've run into.

**Device:** Motorola Moto X4
**Android Version:** 9
**IrisMobile Version:** 2.4.0.1
My device is not rooted and I am not using a custom ROM.

Currently, I have a save file on **exactly** the moment posted by DanielAyo ("No, I can't say I did"). The game immediately resets (and, oddly, turns the volume all the way down) every time I attempt to move forward from this point.

For what it's worth, this happened one time earlier (I believe it was on the "No, I didn't." dialogue bubble asked about by an-error42). I was able to move forward by saving my game a couple of screens before it occurred and trying again. That has not worked this time, however, and (not being a programmer myself) I'm not sure what else to try.
